## Exercise 1 

Given a string. The task is to print all words with even length in the given string.

```
Input: s = "This is a python language"
Output: This
        is
        python
        language 

Input: s = "i am muskan"
Output: am
        muskan

```

In [7]:
def printWords(s):
     s = s.split(' ')
     for word in s:
          if len(word)%2==0:
                print(word)


s = "This is a python language"
print(f"Given string: {s} \nWords with even length: ")
printWords(s)

t = "i am one muskan"
print(f"\nGiven string: {t} \nWords with even length: ")
printWords(t)


Given string: This is a python language 
Words with even length: 
This
is
python
language

Given string: i am one muskan 
Words with even length: 
am
muskan


## Exercise 2 

Sum of a Range of Integers

Write a function, add_it_up(), that takes a single integer as input and returns the sum of the integers from zero to the input parameter.

The function should return 0 if a non-integer is passed in. 

i.e. 

input: 5 
output: 1 + 2 + 3 + 4 + 5  = 15 

input: 5.2 
output: 0

In [13]:
def add_it_up(n):
    if isinstance(n, int):
        tot = sum(range(n+1))
        return f"Sum of integers from 0 to {n} is: {tot}"
    else:
        return f"Not an interger: 0"
    
print(add_it_up(5))
print(add_it_up(5.2))


Sum of integers from 0 to 5 is: 15
Not an interger: 0


# Exercise  

Find all common elements present in each row of a matrix (think Numpy 2D matrix or pandas dataframe) 

```
Input: M × N matrix
 
[  7   1   3   5   3   6  ]
[  2   3   6   1   1   6  ]
[  6   1   7   2   1   4  ]
[  6   6   7   1   3   3  ]
[  5   5   6   1   5   4  ]
[  3   5   6   2   7   1  ]
[  4   1   4   3   6   4  ]
[  4   6   1   7   4   3  ]
 
Output: The common elements are 1 and 6

```

In [15]:
import numpy as np
import pandas as pd

def common_elements(mat):
    mat = np.array(mat)
    common = []
    for i in range(mat.shape[0]):
        common.append(set(mat[i]))
    common = set.intersection(*common)
    return common

mat = [
    [7,1,3,5,3,6],
    [2,3,6,1,1,6],
    [6,1,7,2,1,4],
    [6,6,7,1,3,3],
    [5,5,6,1,5,4],
    [3,5,6,2,7,1],
    [4,1,4,3,6,4],
    [4,6,1,7,4,3]]

print(f"Given matrix: \n{np.array(mat)}")
print(f"\nCommon elements in each row: {common_elements(mat)}")


Given matrix: 
[[7 1 3 5 3 6]
 [2 3 6 1 1 6]
 [6 1 7 2 1 4]
 [6 6 7 1 3 3]
 [5 5 6 1 5 4]
 [3 5 6 2 7 1]
 [4 1 4 3 6 4]
 [4 6 1 7 4 3]]

Common elements in each row: {1, 6}


# Exercise 

Given a value N, find the number of ways to make change for N cents, if we have infinite supply of each of S = { S1, S2, .. , SM } valued coins.

```
Input:
n = 4 , m = 3
S[] = {1,2,3}
Output: 4
Explanation: Four Possible ways are:
{1,1,1,1},{1,1,2},{2,2},{1,3}.
```

```
Input:
n = 10 , m = 4
S[] ={2,5,3,6}
Output: 5
Explanation: Five Possible ways are:
{2,2,2,2,2}, {2,2,3,3}, {2,2,6}, {2,3,5} 
and {5,5}.

```

In [20]:
def count(S, m, n):
    table = [[0 for x in range(m)] for x in range(n+1)]
    for i in range(m):
        table[0][i] = 1
    for i in range(1, n+1):
        for j in range(m):
            x = table[i - S[j]][j] if i-S[j] >= 0 else 0
            y = table[i][j-1] if j >= 1 else 0
            table[i][j] = x + y
    return table[n][m-1]

arr = [1, 2, 3]
m = len(arr)
n = 4
print(f"Given array: {arr} \nNumber of ways to add to {n} with given array: {count(arr, m, n)}")

arr = [2, 5, 3, 6]
m = len(arr)
n = 10
print(f"\nGiven array: {arr} \nNumber of ways to add to {n} with given array: {count(arr, m, n)}")

Given array: [1, 2, 3] 
Number of ways to add to 4 with given array: 4

Given array: [2, 5, 3, 6] 
Number of ways to add to 10 with given array: 5


# Exercise 

 

Generate all the permutations of a string for the given constraint: 
 B doesn't follow A. I.e.  no entries with 'AB'
```
Input : str = “ABC”  
constraint: B doesn't follow A no entries with 'AB'
Output : ACB, BAC, BCA, CBA 
Out of 6 permutations of “ABC”, 4 follow the given constraint and 2 (“ABC” and “CAB”) do not follow. 

Input : str = “BCD” 
Output : BCD, BDC, CDB, CBD, DCB, DBC
```


In [21]:
def permute(s):
    if len(s) == 1:
        return [s]
    perms = permute(s[1:])
    char = s[0]
    result = []
    for perm in perms:
        for i in range(len(perm)+1):
            result.append(perm[:i] + char + perm[i:])
            if i < len(perm) and perm[i] == char:
                break
    return result

s = "ABC"
print(f"Given string: {s} \nPermutations of the string: {permute(s)}")

s = "BCD"
print(f"\nGiven string: {s} \nPermutations of the string: {permute(s)}")



Given string: ABC 
Permutations of the string: ['ABC', 'BAC', 'BCA', 'ACB', 'CAB', 'CBA']

Given string: BCD 
Permutations of the string: ['BCD', 'CBD', 'CDB', 'BDC', 'DBC', 'DCB']
